name: Docker Image

on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Add SHORT_SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up QEMU (for ARM64 emulation)
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image for branch pushes
        if: github.event_name == 'push'
        run: |
          docker buildx build --pull \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ github.ref_name }} \
            --build-arg COMMIT_ID=${{ env.SHORT_SHA }} \
            -t supertypo/kaspa-explorer:${{ env.SHORT_SHA }} \
            -t supertypo/kaspa-explorer:${{ github.ref_name }} \
            -t supertypo/kaspa-explorer:unstable \
            -f docker/Dockerfile \
            --push .

      - name: Build and push Docker image for release
        if: github.event_name == 'release'
        run: |
          docker buildx build --pull \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ github.ref_name }} \
            --build-arg COMMIT_ID=${{ env.SHORT_SHA }} \
            -t supertypo/kaspa-explorer:${{ env.SHORT_SHA }} \
            -t supertypo/kaspa-explorer:${{ github.ref_name }} \
            -t supertypo/kaspa-explorer:latest \
            -f docker/Dockerfile \
            --push .
